<h4><?php echo $this->__('Testimonial') ?></h4>
<?php
	
	/*
		This shows how to load specific fields from a record in the database.
		1) Note the load(15), this corresponds to saying "select * from table where table_id = 15"
		2) You can then just use the get(fieldname) to pull specific data from the table.
		3) If you have a field named news_id, then it becomes getNewsId, etc.
	*/
	/*
	$news = Mage::getModel('testimonial/testimonial')->load(15);
	echo $news->getNewsId();
	echo $news->getTitle();
	echo $news->getContent();
	echo $news->getStatus();
	*/
	
	/*
		This shows an alternate way of loading datas from a record using the database the "Magento Way" (using blocks and controller).
		Uncomment blocks in /app/code/local/Namespace/Module/controllers/IndexController.php if you want to use it.

   */
	/*
	$object = $this->getTestimonial();
	echo 'id: '.$object['test_id'].'<br/>';
	echo 'title: '.$object['title'].'<br/>';
	echo 'content: '.$object['content'].'<br/>';
	echo 'status: '.$object['status'].'<br/>';
	*/            


	/*
		This shows how to load multiple rows in a collection and save a change to them.
		1) The setPageSize function will load only 5 records per page and you can set the current Page with the setCurPage function.
		2) The $collection->walk('save') allows you to save everything in the collection after all changes have been made.
	*/
	/*
	$i = 0;
	
	$collection = Mage::getModel('testimonial/testimonial')->getCollection();
	$collection->setPageSize(5);
	$collection->setCurPage(2);
	$size = $collection->getSize();
	$cnt = count($collection);
	foreach ($collection as $item) {
		$i = $i+1;
		$item->setTitle($i);
		echo $item->getTitle();
	}

	$collection->walk('save');
	*/
	
	/*
		This shows how to load a single record and save a change.
		1) Note the setTitle, this corresponds to the table field name, title, and then you pass it the text to change.
		2) Call the save() function only on a single record.
	*/
	/*
	$object = Mage::getModel('testimonial/testimonial')->load(1);
	$object->setTitle('This is a changed title');
	$object->save();
	*/
	/*
	
	`testimonial_id` int(11) unsigned NOT NULL auto_increment,
  `name` varchar(255) NOT NULL default '',
  `companyname` varchar(255) NOT NULL default '',
  `desigination` varchar(255) NOT NULL default '',
  `profileimage` varchar(255) NOT NULL default '',
  `content` text NOT NULL default '',
	*/
$collection = Mage::getModel('testimonial/testimonial')->getCollection();	
?> 


<div class="category-products">    
	<ol class="products-list" id="products-list">                        
	<?php foreach ($collection as $item) { ?>
		
		<li class="item last even">
			<a href="javascript:void(0)" title="Kaze dama pisa " class="product-image">
					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?><?php echo $item->getProfileimage(); ?>" alt="<?php echo $item->getName(); ?>">
            </a>
			<div class="product-shop">
                <div class="f-fix">
                    <div class="product-primary"><h2 class="product-name"><?php echo $item->getName(); ?></h2></div>                    
                    <div class="product-secondary">						
							<ul class="add-to-links">
								<li><span class="link-wishlist"> <?php echo $item->getDesigination(); ?></a></li>
								<li><span class="separator">|</span> 
								<span class="link-compare"> <?php echo $item->getCompanyname(); ?></a></li>
							</ul>
                    </div>
                    <div class="desc std">
                        <?php echo $item->getContent(); ?>
                    </div>
                </div>
            </div>
        </li>
    
	<?php } ?>
	</ol>
</div>
<?php $configValue = Mage::getStoreConfig('chandantestimonial/testimonial_group/testimonial_frontend'); ?>
<?php if($configValue==1){ ?>
<div class="buttons-set">
	<p class="back-link"><a onClick="Javascript:history.back();" class="back-link"><small>« </small>Back</a></p>
	<a title="Add New Testimonial" class="button" href="<?php echo $this->getUrl() ?>testimonial/index/createpost/"><span><span>Add New Testimonial</span></span></a>
</div>
<?php } ?>
